package adaptors.usecase

import adaptors.repository.{PostRepositoryComponentImpl, UserRepositoryComponentImpl}
import usecases.createRelatedPost.CreateRelatedPostInteractor

object CreateRelatedPostUseCase extends CreateRelatedPostInteractor with PostRepositoryComponentImpl with UserRepositoryComponentImpl

