package adaptors.usecase

import adaptors.repository.UsesPostRepository
import usecases.getrelatedposts.GetRelatedPostsInteractor

object GetRelatedPostsInputBoundaryImpl extends GetRelatedPostsInteractor with UsesPostRepository
