package adaptors.usecase

import adaptors.repository.PostRepositoryComponentImpl
import usecases.getrelatedposts.GetRelatedPostsInteractor

object GetRelatedPostsInputBoundaryImpl extends GetRelatedPostsInteractor with PostRepositoryComponentImpl
